spring:
  datasource:
    url: jdbc:postgresql://172.20.7.53:5432/db2992_16?currentSchema=kursovoi
    username: st2992
    password: pwd2992
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use-new-id-generator-mappings: false
        jdbc:
          lob:
            non-contextual-creation: true
      type:
        use-before-10-behavior: false
        use-new-id-generator-mappings: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.shoeshop: DEBUG